/**
 * Field Operations - Work Order Mock Data
 */

import { WorkOrderRecord, WorkOrderStatus, WorkOrderPriority, WorkOrderType } from "./work-order-types";

export const MOCK_WORK_ORDERS: WorkOrderRecord[] = [
  {
    workOrderId: "WO-20260313-0001",
    deviceId: "BISD001",
    customerName: "서울시 대중교통",
    regionName: "서울",
    groupName: "강남역 그룹",
    busStopName: "강남역 1번 출구",
    priority: "CRITICAL",
    status: "IN_PROGRESS",
    workOrderType: "EMERGENCY_REPAIR",
    assignedTechnicianId: "TECH001",
    assignedTechnicianName: "김철수",
    createdAt: new Date("2026-03-13T08:00:00"),
    scheduledStartTime: new Date("2026-03-13T09:00:00"),
    scheduledDurationHours: 2,
    actualStartTime: new Date("2026-03-13T09:15:00"),
    lastUpdatedAt: new Date("2026-03-13T11:30:00"),
    lastUpdatedBy: "김철수",
    description: "디스플레이 화면 오작동 - 부팅 반복",
    estimatedCost: 150000,
    actualCost: 150000,
    notes: "메인보드 교체 완료, 테스트 중",
    attachmentUrls: ["https://example.com/photo1.jpg"],
    relatedIncidentIds: ["INC-20260313-0001"],
  },
  {
    workOrderId: "WO-20260313-0002",
    deviceId: "BISD002",
    customerName: "부산시 대중교통",
    regionName: "부산",
    groupName: "부산역 그룹",
    busStopName: "부산역 2번 출구",
    priority: "HIGH",
    status: "ASSIGNED",
    workOrderType: "PREVENTIVE_MAINTENANCE",
    assignedTechnicianId: "TECH002",
    assignedTechnicianName: "이영희",
    createdAt: new Date("2026-03-12T14:00:00"),
    scheduledStartTime: new Date("2026-03-14T10:00:00"),
    scheduledDurationHours: 1.5,
    lastUpdatedAt: new Date("2026-03-13T10:00:00"),
    lastUpdatedBy: "관리자",
    description: "월간 정기 점검 및 청소",
    estimatedCost: 50000,
    notes: "배터리 상태 점검 포함",
  },
  {
    workOrderId: "WO-20260313-0003",
    deviceId: "BISD003",
    customerName: "대구시 대중교통",
    regionName: "대구",
    groupName: "대구역 그룹",
    busStopName: "대구역 3번 출구",
    priority: "MEDIUM",
    status: "CREATED",
    workOrderType: "CORRECTIVE_MAINTENANCE",
    assignedTechnicianId: "",
    assignedTechnicianName: "미배정",
    createdAt: new Date("2026-03-13T12:00:00"),
    scheduledStartTime: new Date("2026-03-15T14:00:00"),
    scheduledDurationHours: 1,
    lastUpdatedAt: new Date("2026-03-13T12:00:00"),
    lastUpdatedBy: "관리자",
    description: "USB 포트 접촉 불량 수리",
    estimatedCost: 80000,
  },
  {
    workOrderId: "WO-20260313-0004",
    deviceId: "BISD004",
    customerName: "인천시 대중교통",
    regionName: "인천",
    groupName: "인천공항 그룹",
    busStopName: "인천공항 T1",
    priority: "LOW",
    status: "COMPLETED",
    workOrderType: "INSPECTION",
    assignedTechnicianId: "TECH003",
    assignedTechnicianName: "박준호",
    createdAt: new Date("2026-03-10T09:00:00"),
    scheduledStartTime: new Date("2026-03-11T10:00:00"),
    scheduledDurationHours: 1,
    actualStartTime: new Date("2026-03-11T10:05:00"),
    actualCompletionTime: new Date("2026-03-11T11:00:00"),
    lastUpdatedAt: new Date("2026-03-11T11:00:00"),
    lastUpdatedBy: "박준호",
    description: "분기별 안전 점검",
    estimatedCost: 40000,
    actualCost: 40000,
    notes: "모든 항목 정상",
  },
  {
    workOrderId: "WO-20260312-0005",
    deviceId: "BISD005",
    customerName: "광주시 대중교통",
    regionName: "광주",
    groupName: "광주역 그룹",
    busStopName: "광주역 1번 출구",
    priority: "HIGH",
    status: "IN_PROGRESS",
    workOrderType: "PARTS_REPLACEMENT",
    assignedTechnicianId: "TECH001",
    assignedTechnicianName: "김철수",
    createdAt: new Date("2026-03-12T11:00:00"),
    scheduledStartTime: new Date("2026-03-13T13:00:00"),
    scheduledDurationHours: 1.5,
    actualStartTime: new Date("2026-03-13T13:15:00"),
    lastUpdatedAt: new Date("2026-03-13T14:45:00"),
    lastUpdatedBy: "김철수",
    description: "배터리 팩 교체",
    estimatedCost: 200000,
    actualCost: 200000,
    notes: "배터리 교체 진행 중, 충방전 테스트 예정",
  },
  {
    workOrderId: "WO-20260312-0006",
    deviceId: "BISD006",
    customerName: "대전시 대중교통",
    regionName: "대전",
    groupName: "대전역 그룹",
    busStopName: "대전역 2번 출구",
    priority: "CRITICAL",
    status: "FAILED",
    workOrderType: "CORRECTIVE_MAINTENANCE",
    assignedTechnicianId: "TECH004",
    assignedTechnicianName: "최민지",
    createdAt: new Date("2026-03-11T08:00:00"),
    scheduledStartTime: new Date("2026-03-12T10:00:00"),
    scheduledDurationHours: 2,
    actualStartTime: new Date("2026-03-12T10:00:00"),
    actualCompletionTime: new Date("2026-03-12T12:00:00"),
    lastUpdatedAt: new Date("2026-03-12T12:00:00"),
    lastUpdatedBy: "최민지",
    description: "메인보드 고장 - 교체 필요",
    estimatedCost: 250000,
    actualCost: 0,
    notes: "부품 재고 부족으로 실패, 재주문 필요",
  },
  {
    workOrderId: "WO-20260313-0007",
    deviceId: "BISD007",
    customerName: "울산시 대중교통",
    regionName: "울산",
    groupName: "울산역 그룹",
    busStopName: "울산역 1번 출구",
    priority: "MEDIUM",
    status: "VERIFIED",
    workOrderType: "CORRECTIVE_MAINTENANCE",
    assignedTechnicianId: "TECH002",
    assignedTechnicianName: "이영희",
    createdAt: new Date("2026-03-10T09:00:00"),
    scheduledStartTime: new Date("2026-03-11T14:00:00"),
    scheduledDurationHours: 1,
    actualStartTime: new Date("2026-03-11T14:10:00"),
    actualCompletionTime: new Date("2026-03-11T15:05:00"),
    lastUpdatedAt: new Date("2026-03-11T15:30:00"),
    lastUpdatedBy: "검증담당자",
    description: "터치스크린 반응 속도 개선",
    estimatedCost: 100000,
    actualCost: 100000,
    notes: "작업 검증 완료",
  },
  {
    workOrderId: "WO-20260313-0008",
    deviceId: "BISD008",
    customerName: "경기도 대중교통",
    regionName: "경기",
    groupName: "수원역 그룹",
    busStopName: "수원역 3번 출구",
    priority: "LOW",
    status: "CANCELLED",
    workOrderType: "PREVENTIVE_MAINTENANCE",
    assignedTechnicianId: "TECH003",
    assignedTechnicianName: "박준호",
    createdAt: new Date("2026-03-08T09:00:00"),
    scheduledStartTime: new Date("2026-03-14T10:00:00"),
    scheduledDurationHours: 1,
    lastUpdatedAt: new Date("2026-03-13T09:00:00"),
    lastUpdatedBy: "관리자",
    description: "정기 점검 (장비 이전으로 취소됨)",
    estimatedCost: 50000,
    notes: "장비 이전됨으로 인해 작업 취소",
  },
];

export function buildWorkOrderSummary(orders: WorkOrderRecord[]) {
  return {
    total: orders.length,
    byStatus: {
      CREATED: orders.filter((o) => o.status === "CREATED").length,
      ASSIGNED: orders.filter((o) => o.status === "ASSIGNED").length,
      IN_PROGRESS: orders.filter((o) => o.status === "IN_PROGRESS").length,
      COMPLETED: orders.filter((o) => o.status === "COMPLETED").length,
      VERIFIED: orders.filter((o) => o.status === "VERIFIED").length,
      FAILED: orders.filter((o) => o.status === "FAILED").length,
      CANCELLED: orders.filter((o) => o.status === "CANCELLED").length,
    },
    delayed: orders.filter((o) => {
      if (!o.actualStartTime) return false;
      const scheduled = new Date(o.scheduledStartTime);
      return o.actualStartTime > new Date(scheduled.getTime() + 15 * 60000);
    }).length,
    urgent: orders.filter((o) => o.priority === "CRITICAL" && (o.status === "CREATED" || o.status === "ASSIGNED")).length,
  };
}
