import type {
  CommunicationHealthRecord,
  CommunicationHealthSummary,
  CommunicationDiagnostic,
} from "@/lib/rms/communication-health-types";

export const MOCK_COMMUNICATION_HEALTH: CommunicationHealthRecord[] = [
  {
    deviceId: "DEV001",
    bisDeviceId: "BISD001",
    customerId: "CUST001",
    customerName: "서울특별시 버스운영사",
    region: "서울",
    group: "강서지역",
    busStopName: "강서역 1번출구",
    communicationStatus: "CONNECTED",
    networkType: "LTE",
    latencyMs: 45,
    packetLossPercent: 0,
    signalStrengthDbm: -65,
    lastHeartbeatTime: new Date(Date.now() - 30000).toISOString(),
    lastHeartbeatAgoSeconds: 30,
    heartbeatIntervalSeconds: 60,
    failureCount: 0,
    lastFailureTime: null,
    gatewayStatus: "ONLINE",
    gatewayLatencyMs: 25,
    lastUpdated: new Date().toISOString(),
    displayState: "NORMAL",
  },
  {
    deviceId: "DEV002",
    bisDeviceId: "BISD002",
    customerId: "CUST001",
    customerName: "서울특별시 버스운영사",
    region: "서울",
    group: "강서지역",
    busStopName: "강서역 2번출구",
    communicationStatus: "DEGRADED",
    networkType: "LTE",
    latencyMs: 185,
    packetLossPercent: 3.2,
    signalStrengthDbm: -85,
    lastHeartbeatTime: new Date(Date.now() - 45000).toISOString(),
    lastHeartbeatAgoSeconds: 45,
    heartbeatIntervalSeconds: 60,
    failureCount: 1,
    lastFailureTime: new Date(Date.now() - 300000).toISOString(),
    gatewayStatus: "ONLINE",
    gatewayLatencyMs: 95,
    lastUpdated: new Date().toISOString(),
    displayState: "DEGRADED",
  },
  {
    deviceId: "DEV003",
    bisDeviceId: "BISD003",
    customerId: "CUST001",
    customerName: "서울특별시 버스운영사",
    region: "강남",
    group: "강남지역",
    busStopName: "강남역 지하철역사",
    communicationStatus: "LOST",
    networkType: "WiFi",
    latencyMs: 0,
    packetLossPercent: 100,
    signalStrengthDbm: -120,
    lastHeartbeatTime: new Date(Date.now() - 1800000).toISOString(),
    lastHeartbeatAgoSeconds: 1800,
    heartbeatIntervalSeconds: 60,
    failureCount: 12,
    lastFailureTime: new Date(Date.now() - 120000).toISOString(),
    gatewayStatus: "OFFLINE",
    gatewayLatencyMs: 0,
    lastUpdated: new Date().toISOString(),
    displayState: "OFFLINE",
  },
  {
    deviceId: "DEV004",
    bisDeviceId: "BISD004",
    customerId: "CUST002",
    customerName: "인천광역시 버스운영사",
    region: "인천",
    group: "인천지역",
    busStopName: "인천터미널 정류장",
    communicationStatus: "CONNECTED",
    networkType: "4G",
    latencyMs: 52,
    packetLossPercent: 0.5,
    signalStrengthDbm: -70,
    lastHeartbeatTime: new Date(Date.now() - 25000).toISOString(),
    lastHeartbeatAgoSeconds: 25,
    heartbeatIntervalSeconds: 60,
    failureCount: 0,
    lastFailureTime: null,
    gatewayStatus: "ONLINE",
    gatewayLatencyMs: 28,
    lastUpdated: new Date().toISOString(),
    displayState: "NORMAL",
  },
  {
    deviceId: "DEV005",
    bisDeviceId: "BISD005",
    customerId: "CUST002",
    customerName: "인천광역시 버스운영사",
    region: "인천",
    group: "인천지역",
    busStopName: "인천공항 대로",
    communicationStatus: "DEGRADED",
    networkType: "LTE",
    latencyMs: 245,
    packetLossPercent: 5.8,
    signalStrengthDbm: -95,
    lastHeartbeatTime: new Date(Date.now() - 78000).toISOString(),
    lastHeartbeatAgoSeconds: 78,
    heartbeatIntervalSeconds: 60,
    failureCount: 3,
    lastFailureTime: new Date(Date.now() - 600000).toISOString(),
    gatewayStatus: "CONNECTING",
    gatewayLatencyMs: 142,
    lastUpdated: new Date().toISOString(),
    displayState: "DEGRADED",
  },
  {
    deviceId: "DEV006",
    bisDeviceId: "BISD006",
    customerId: "CUST003",
    customerName: "경기도 버스운영사",
    region: "경기",
    group: "수원지역",
    busStopName: "수원역 버스정류장",
    communicationStatus: "CONNECTED",
    networkType: "WiFi",
    latencyMs: 38,
    packetLossPercent: 0,
    signalStrengthDbm: -55,
    lastHeartbeatTime: new Date(Date.now() - 35000).toISOString(),
    lastHeartbeatAgoSeconds: 35,
    heartbeatIntervalSeconds: 60,
    failureCount: 0,
    lastFailureTime: null,
    gatewayStatus: "ONLINE",
    gatewayLatencyMs: 18,
    lastUpdated: new Date().toISOString(),
    displayState: "NORMAL",
  },
  {
    deviceId: "DEV007",
    bisDeviceId: "BISD007",
    customerId: "CUST003",
    customerName: "경기도 버스운영사",
    region: "경기",
    group: "성남지역",
    busStopName: "판교역 정류소",
    communicationStatus: "CONNECTED",
    networkType: "LTE",
    latencyMs: 58,
    packetLossPercent: 0.2,
    signalStrengthDbm: -68,
    lastHeartbeatTime: new Date(Date.now() - 32000).toISOString(),
    lastHeartbeatAgoSeconds: 32,
    heartbeatIntervalSeconds: 60,
    failureCount: 0,
    lastFailureTime: null,
    gatewayStatus: "ONLINE",
    gatewayLatencyMs: 32,
    lastUpdated: new Date().toISOString(),
    displayState: "NORMAL",
  },
  {
    deviceId: "DEV008",
    bisDeviceId: "BISD008",
    customerId: "CUST004",
    customerName: "대구광역시 버스운영사",
    region: "대구",
    group: "대구중심",
    busStopName: "대구역 광장",
    communicationStatus: "DEGRADED",
    networkType: "4G",
    latencyMs: 165,
    packetLossPercent: 2.1,
    signalStrengthDbm: -78,
    lastHeartbeatTime: new Date(Date.now() - 92000).toISOString(),
    lastHeartbeatAgoSeconds: 92,
    heartbeatIntervalSeconds: 60,
    failureCount: 2,
    lastFailureTime: new Date(Date.now() - 480000).toISOString(),
    gatewayStatus: "ONLINE",
    gatewayLatencyMs: 78,
    lastUpdated: new Date().toISOString(),
    displayState: "DEGRADED",
  },
  {
    deviceId: "DEV009",
    bisDeviceId: "BISD009",
    customerId: "CUST004",
    customerName: "대구광역시 버스운영사",
    region: "대구",
    group: "대구남부",
    busStopName: "남대구역 버스터미널",
    communicationStatus: "CONNECTED",
    networkType: "LTE",
    latencyMs: 42,
    packetLossPercent: 0,
    signalStrengthDbm: -62,
    lastHeartbeatTime: new Date(Date.now() - 28000).toISOString(),
    lastHeartbeatAgoSeconds: 28,
    heartbeatIntervalSeconds: 60,
    failureCount: 0,
    lastFailureTime: null,
    gatewayStatus: "ONLINE",
    gatewayLatencyMs: 22,
    lastUpdated: new Date().toISOString(),
    displayState: "NORMAL",
  },
  {
    deviceId: "DEV010",
    bisDeviceId: "BISD010",
    customerId: "CUST005",
    customerName: "부산광역시 버스운영사",
    region: "부산",
    group: "부산중심",
    busStopName: "부산역 광장",
    communicationStatus: "LOST",
    networkType: "LTE",
    latencyMs: 0,
    packetLossPercent: 100,
    signalStrengthDbm: -115,
    lastHeartbeatTime: new Date(Date.now() - 3600000).toISOString(),
    lastHeartbeatAgoSeconds: 3600,
    heartbeatIntervalSeconds: 60,
    failureCount: 18,
    lastFailureTime: new Date(Date.now() - 240000).toISOString(),
    gatewayStatus: "ERROR",
    gatewayLatencyMs: 0,
    lastUpdated: new Date().toISOString(),
    displayState: "OFFLINE",
  },
  {
    deviceId: "DEV011",
    bisDeviceId: "BISD011",
    customerId: "CUST005",
    customerName: "부산광역시 버스운영사",
    region: "부산",
    group: "부산북부",
    busStopName: "북부산역 정류소",
    communicationStatus: "CONNECTED",
    networkType: "WiFi",
    latencyMs: 35,
    packetLossPercent: 0,
    signalStrengthDbm: -58,
    lastHeartbeatTime: new Date(Date.now() - 31000).toISOString(),
    lastHeartbeatAgoSeconds: 31,
    heartbeatIntervalSeconds: 60,
    failureCount: 0,
    lastFailureTime: null,
    gatewayStatus: "ONLINE",
    gatewayLatencyMs: 20,
    lastUpdated: new Date().toISOString(),
    displayState: "NORMAL",
  },
  {
    deviceId: "DEV012",
    bisDeviceId: "BISD012",
    customerId: "CUST001",
    customerName: "서울특별시 버스운영사",
    region: "서울",
    group: "강남지역",
    busStopName: "서초역 정류장",
    communicationStatus: "DEGRADED",
    networkType: "4G",
    latencyMs: 215,
    packetLossPercent: 4.3,
    signalStrengthDbm: -88,
    lastHeartbeatTime: new Date(Date.now() - 105000).toISOString(),
    lastHeartbeatAgoSeconds: 105,
    heartbeatIntervalSeconds: 60,
    failureCount: 5,
    lastFailureTime: new Date(Date.now() - 360000).toISOString(),
    gatewayStatus: "ONLINE",
    gatewayLatencyMs: 105,
    lastUpdated: new Date().toISOString(),
    displayState: "DEGRADED",
  },
];

export function buildCommunicationSummary(
  records: CommunicationHealthRecord[]
): CommunicationHealthSummary {
  const summary: CommunicationHealthSummary = {
    total: records.length,
    connected: 0,
    degraded: 0,
    lost: 0,
    increasingLatency: 0,
    increasingPacketLoss: 0,
    unstable: 0,
  };

  records.forEach((record) => {
    switch (record.communicationStatus) {
      case "CONNECTED":
        summary.connected++;
        break;
      case "DEGRADED":
        summary.degraded++;
        break;
      case "LOST":
        summary.lost++;
        break;
    }

    if (record.latencyMs > 150) summary.increasingLatency++;
    if (record.packetLossPercent > 3) summary.increasingPacketLoss++;
    if (record.failureCount > 2) summary.unstable++;
  });

  return summary;
}

export function getHeartbeatStatus(
  agoSeconds: number,
  expectedIntervalSeconds: number
): "on-time" | "delayed" | "overdue" {
  if (agoSeconds <= expectedIntervalSeconds) return "on-time";
  if (agoSeconds <= expectedIntervalSeconds * 1.5) return "delayed";
  return "overdue";
}
